# Generated by Django 3.2.9 on 2021-12-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('descriptions', models.CharField(max_length=500)),
            ],
        ),
    ]
