# Generated by Django 3.2.9 on 2021-12-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='summary',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
